default: &default
  config:
    secret_key_base: 6293c35deb097551e2468193395c613f93580bdda63b9e94e1b559f0d17d5ec37e452dee3f02ddffe6b662245de9252fb9b8b8adf0e0dc0b60205e5c2b83fdf0
    registerable: true
    confirmable: false
    mailer_sender: notifications@wotwhere.com
    mailer_url_options:
      host: localhost
      port: 3000
    smtp_settings:
      address: smtp.gmail.com
      port: 587
      domain: beaconctrl.wotwhere.com
      user_name: notifications@wotwhere.com
      password: 9k84ka0JD$uhLej3
      authentication: plain
      enable_starttls_auto: true
    system_mailer_receiver: notifications@wotwhere.com
    redis_url: redis://localhost:6379
    create_test_app_on_new_account: true
    autoload_extensions:
      "Analytics":  true
      "DwellTime":  true
      "Kontakt.io": true
      "Presence":   true

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default